import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { rollup } from "rollup";
import dts from "rollup-plugin-dts";
import { build as viteBuild } from "vite";

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoDir = resolve(packageDir, "../..");
const distDir = resolve(packageDir, "dist");

const packageManifest = JSON.parse(
  await readFile(resolve(packageDir, "package.json"), "utf8"),
);
const workspaceSources = new Map([
  ["@ten4seven/icons", resolve(repoDir, "packages/icons/src/index.tsx")],
  ["@ten4seven/tokens", resolve(repoDir, "packages/tokens/src/index.ts")],
]);

await rm(distDir, { force: true, recursive: true });

await viteBuild({
  configFile: resolve(packageDir, "vite.config.ts"),
  root: packageDir,
});

const declarationBundle = await rollup({
  input: resolve(packageDir, "src/index.ts"),
  plugins: [
    {
      name: "ten4seven-workspace-declaration-aliases",
      resolveId(source) {
        return workspaceSources.get(source) ?? null;
      },
    },
    dts({ respectExternal: false }),
  ],
});

try {
  await declarationBundle.write({
    file: resolve(distDir, "index.d.ts"),
    format: "es",
  });
} finally {
  await declarationBundle.close();
}

const [themeCss, componentCss] = await Promise.all([
  readFile(resolve(repoDir, "packages/tokens/src/theme.css"), "utf8"),
  readFile(resolve(packageDir, "src/styles.css"), "utf8"),
]);

await writeFile(
  resolve(distDir, "styles.css"),
  [
    "/* Generated by @ten4seven/ui. Tokens precede component contracts. */",
    themeCss.trim(),
    componentCss.trim(),
    "",
  ].join("\n\n"),
  "utf8",
);

const fontsDir = resolve(distDir, "fonts");
await mkdir(fontsDir, { recursive: true });
const fontArtifacts = [
  "DM-Sans-OFL.txt",
  "DM-Sans-Variable.woff2",
  "IBM-Plex-Mono-400.woff2",
  "IBM-Plex-Mono-500.woff2",
  "IBM-Plex-Mono-600.woff2",
  "IBM-Plex-Mono-700.woff2",
  "IBM-Plex-Mono-OFL.txt",
  "Inter-OFL.txt",
  "Inter-Variable.woff2",
  "Source-Serif-4-OFL.txt",
  "Source-Serif-4-Variable.woff2",
];
await Promise.all(
  fontArtifacts.map((artifact) =>
    copyFile(
      resolve(repoDir, "packages/tokens/src/fonts", artifact),
      resolve(fontsDir, artifact),
    ),
  ),
);

await writeFile(
  resolve(distDir, "package-build.json"),
  `${JSON.stringify(
    {
      name: packageManifest.name,
      version: packageManifest.version,
      entry: "index.js",
      commonjsEntry: "index.cjs",
      declarations: "index.d.ts",
      stylesheet: "styles.css",
      includes: [
        "tokens",
        "semantic-icons",
        "react-components",
        "motion",
        "self-hosted-fonts",
      ],
    },
    null,
    2,
  )}\n`,
  "utf8",
);

console.log(
  `Built ${packageManifest.name}@${packageManifest.version} at ${distDir}`,
);
